pid logs/sitio3.pid;
events{
	worker_connections 1024;
}
http {
	server {
		listen 83;
		location / {
			root /mnt/c/Users/antip/Documents/data/17349/nginx/3sitios/sitio3;
			index index.html;
		}
	}
}

